#!/bin/bash




gnome-terminal -- bash -i -c "sleep 3;roscore;exec bash"
sleep 10




# 设置权限并运行 rosserial
gnome-terminal -- bash -i -c "sleep 3;sudo chmod 666 /dev/ttyACM0; sleep 3;rosrun rosserial_python serial_node.py /dev/ttyACM0; exec bash"

# 等待 rosserial 启动
sleep 10

# 运行 Python 脚本
gnome-terminal -- bash -i -c "sleep 3;python3 ~/ros_comm_ws/src/rccar_comm/src/RosControlArduino_Class.py; exec bash"






///////////////////////////////////////



#!/usr/bin/env python3
import os
import time
import subprocess

# 启动 roscore
subprocess.Popen(['roscore'])
time.sleep(10)

# 启动 rosserial
subprocess.Popen(['sudo', 'chmod', '666', '/dev/ttyACM0'])
time.sleep(3)
subprocess.Popen(['rosrun', 'rosserial_python', 'serial_node.py', '/dev/ttyACM0'])

# 等待 rosserial 启动
time.sleep(10)

# 启动 Python 脚本
subprocess.Popen(['python3', os.path.expanduser('~/ros_comm_ws/src/rccar_comm/src/RosControlArduino_Class.py')])

# 保持脚本运行
while True:
    time.sleep(1)




//
<launch>
    <!-- 启动自定义脚本 -->
    <node pkg="rccar_comm" type="start_ros_nodes.py" name="start_ros_nodes" output="screen"/>
</launch>

