#!/bin/bash




gnome-terminal -- bash -i -c "sleep 3;roscore;exec bash"
sleep 10




# 设置权限并运行 rosserial
gnome-terminal -- bash -i -c "sleep 3;sudo chmod 666 /dev/ttyACM0; sleep 3;rosrun rosserial_python serial_node.py /dev/ttyACM0; exec bash"

# 等待 rosserial 启动
sleep 10

# 运行 Python 脚本
gnome-terminal -- bash -i -c "sleep 3;python3 ~/ros_comm_ws/src/rccar_comm/src/RosControlArduino_Class.py; exec bash"
